services:
  fw-web:
    build:
      context: .
      args:
        TORCH_INDEX_URL: ${TORCH_INDEX_URL:-https://download.pytorch.org/whl/cu128}
    container_name: fw-web
    ports:
      - "8000:8000"
    gpus: all
    environment:
      - HF_HOME=/hf
    volumes:
      # SMB share mount (credentials in .env)
      - "media-share:/work/in"

      # output na hosta (w tym folderze projektu utworz ./out)
      - "./out:/work/out"

      # cache modeli HF
      - "fw-hf-cache:/hf"

volumes:
  fw-hf-cache:
  media-share:
    driver: local
    driver_opts:
      type: cifs
      device: "${SMB_SHARE}"
      o: "username=${SMB_USER},password=${SMB_PASS},${SMB_OPTS}"
